### ISSUE TITLE
Port this to Google Cloud Run

### ISSUE THREAD

**Issue by simonw** [simonw/cryptozoology#21]
This needs spatialite so I don't think I can run it on Zeit Now v2.

**Comment by simonw** [comment]
I'll use the same process as https://github.com/simonw/global-power-plants-datasette/issues/1

**Comment by simonw** [comment]
I added the Cloud Run secrets to this repo.

**Comment by simonw** [comment]
Now adding a GitHub Actions definition based on https://github.com/simonw/global-power-plants-datasette/blob/a65a24c193cbbc708d05094f6b6a34b77509b880/.github/workflows/scheduled.yml

**Comment by simonw** [comment]
https://github.com/simonw/cryptozoology/runs/572567171?check_suite_focus=true
```
  Downloading Shapely-1.6.4.post2.tar.gz (225 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/hostedtoolcache/Python/3.8.2/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kdthwu0_/Shapely/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kdthwu0_/Shapely/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-kdthwu0_/Shapely/pip-egg-info
         cwd: /tmp/pip-install-kdthwu0_/Shapely/
    Complete output (11 lines):
    Failed `CDLL(libgeos_c.so.1)`
    Failed `CDLL(libgeos_c.so)`
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kdthwu0_/Shapely/setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "/tmp/pip-install-kdthwu0_/Shapely/shapely/_buildcfg.py", line 166, in <module>
        lgeos = load_dll('geos_c',
      File "/tmp/pip-install-kdthwu0_/Shapely/shapely/_buildcfg.py", line 159, in load_dll
        raise OSError(
    OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
##[error]Process completed with exit code 1.
```

**Comment by simonw** [comment]
https://github.com/simonw/cryptozoology/runs/572569914?check_suite_focus=true
```
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
```

**Comment by simonw** [comment]
Ugh, this error is nasty: https://github.com/simonw/cryptozoology/runs/572590395?check_suite_focus=true

```
  File "build_cryptids_database.py", line 52, in build_database
    conn.enable_load_extension(True)
AttributeError: 'sqlite3.Connection' object has no attribute 'enable_load_extension'
```

https://stackoverflow.com/questions/58892028/sqlite3-connection-object-has-no-attribute-enable-load-extension

**Comment by simonw** [comment]
This may be a problem with `sqlite3` in GitHub Actions generally: https://github.com/actions/setup-python/issues/49 and https://github.com/actions/virtual-environments/issues/317

**Comment by simonw** [comment]
I'll try fixing that with https://github.com/coleifer/pysqlite3

**Comment by leachcoding** [comment]
Would this maybe help? https://code.luasoftware.com/tutorials/python/python-sqlite3-connection-objecthas-no-attribute-enable-load-extension/

**Comment by simonw** [comment]
I think pysqlite3 is working, but now I need to figure out the right path to the loadable module. It apparently isn't any of these:

https://github.com/simonw/cryptozoology/blob/f12d4509781efa6398fd64b88e68e27fb0f7edd5/build_cryptids_database.py#L16-L22

Here's a clue though: https://packages.ubuntu.com/xenial/amd64/libsqlite3-mod-spatialite/filelist

**Comment by simonw** [comment]
The build worked! Deploy failed on `datasette: command not found` because I forgot to install Datasette.

**Comment by simonw** [comment]
It's live! https://cryptids-j7hipcg4aq-uc.a.run.app/ - just need to handle DNS now.

**Comment by simonw** [comment]
So this API works now: https://cryptids-j7hipcg4aq-uc.a.run.app/cryptids/by_point?longitude=-87.6298&latitude=41.8781

**Comment by simonw** [comment]
I set up the mapping in the Google Cloud Console:

<img width="589" alt="Domain_mappings_–_Cloud_Run_–_datasette_–_Google_Cloud_Platform" src="https://user-images.githubusercontent.com/9599/78848782-a01e1400-79c7-11ea-9e18-75a2525ad7e5.png">

And the CNAME in CloudFlare:

<img width="1053" alt="DNS___datasettes_com___Account___Cloudflare_-_Web_Performance___Security" src="https://user-images.githubusercontent.com/9599/78848829-bb891f00-79c7-11ea-8df2-46b23ed3bdd8.png">

Hopefully will start working in a few minutes.

**Comment by simonw** [comment]
I'm now seeing it at https://cryptids.datasettes.com/
